name: global_chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.2.1
  provider: ^6.1.2
  intl: ^0.18.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  # emoji_picker_flutter: ^1.0.0 # Removed
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
