// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:global_chat_app/main.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEGJ6c8-M2m9Oc3Txv5o3HUGVXW50H4cI',
    appId: '1:1027771984170:web:584349d5140e03f9e75653',
    messagingSenderId: '1027771984170',
    projectId: 'mychatapp-aa3b3',
    authDomain: 'mychatapp-aa3b3.firebaseapp.com',
    storageBucket: 'mychatapp-aa3b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhv1XyGtEhmBN3D0H91RNxdGDYspYhDi8',
    appId: '1:1027771984170:android:5dfaf2580311b93be75653',
    messagingSenderId: '1027771984170',
    projectId: 'mychatapp-aa3b3',
    storageBucket: 'mychatapp-aa3b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1rT55jPkspUsm-aCJNMr8pfRBqRVRdqg',
    appId: '1:1027771984170:ios:95a17e5b56e9a9dbe75653',
    messagingSenderId: '1027771984170',
    projectId: 'mychatapp-aa3b3',
    storageBucket: 'mychatapp-aa3b3.appspot.com',
    iosBundleId: 'com.example.globalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1rT55jPkspUsm-aCJNMr8pfRBqRVRdqg',
    appId: '1:1027771984170:ios:95a17e5b56e9a9dbe75653',
    messagingSenderId: '1027771984170',
    projectId: 'mychatapp-aa3b3',
    storageBucket: 'mychatapp-aa3b3.appspot.com',
    iosBundleId: 'com.example.globalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEGJ6c8-M2m9Oc3Txv5o3HUGVXW50H4cI',
    appId: '1:1027771984170:web:c140063b097ab0fce75653',
    messagingSenderId: '1027771984170',
    projectId: 'mychatapp-aa3b3',
    authDomain: 'mychatapp-aa3b3.firebaseapp.com',
    storageBucket: 'mychatapp-aa3b3.appspot.com',
  );

  static runApp(MyApp myApp) {}
}
